#!/usr/bin/env bash
# Desinstala lo creado por install.sh. Funciona sin la release extraída: el
# instalador deja una copia en ~/.local/share/guionar/uninstall.sh y el
# comando guionar-uninstall apunta a ella. Nunca toca copias del repositorio
# ni sus entornos virtuales. Por defecto conserva la configuración.
set -euo pipefail

main() {
DATA_BASE="${XDG_DATA_HOME:-$HOME/.local/share}"
CONFIG_BASE="${XDG_CONFIG_HOME:-$HOME/.config}"
# La copia instalada se reconoce por installed.json a su lado: desinstala la
# raíz donde vive aunque XDG_DATA_HOME haya cambiado desde la instalación.
PROPIO_DIR="$(dirname -- "$(readlink -f -- "${BASH_SOURCE[0]}")")"
RAIZ_PREDETERMINADA="$DATA_BASE/guionar"
if [[ -z "${GUIONAR_INSTALL_HOME:-}" && "$(basename -- "$PROPIO_DIR")" == guionar \
        && -f "$PROPIO_DIR/installed.json" && -f "$PROPIO_DIR/uninstall.sh" ]]; then
    RAIZ_PREDETERMINADA="$PROPIO_DIR"
fi
INSTALL_HOME_ORIGINAL="${GUIONAR_INSTALL_HOME:-$RAIZ_PREDETERMINADA}"
INSTALL_HOME="$INSTALL_HOME_ORIGINAL"
BIN_DIR="${GUIONAR_BIN_DIR:-$HOME/.local/bin}"
DESKTOP_PATH="$DATA_BASE/applications/guionar.desktop"
ICON_PATH="$DATA_BASE/icons/hicolor/scalable/apps/guionar.svg"
CONFIG_DIR="$CONFIG_BASE/guionar"
MARCA="# Generated by GuionAR install.sh."
PURGE_DATA=0

uso() {
    cat <<'TXT'
Uso: guionar-uninstall [--purge-data]
     ./uninstall.sh [--purge-data]

Desinstala GuionAR de la cuenta de usuario.
Por defecto conserva la configuración (~/.config/guionar).

  --purge-data  elimina también la configuración de GuionAR
  -h, --help    muestra esta ayuda sin modificar el sistema

Nunca borra una copia del repositorio de GuionAR ni su entorno .venv.
TXT
}

while (($#)); do
    case "$1" in
        --purge-data) PURGE_DATA=1 ;;
        -h|--help) uso; exit 0 ;;
        *) echo "!! opción desconocida: $1" >&2; uso >&2; exit 2 ;;
    esac
    shift
done

while [[ "$INSTALL_HOME" != "/" && "$INSTALL_HOME" == */ ]]; do
    INSTALL_HOME="${INSTALL_HOME%/}"
done
case "$INSTALL_HOME" in
    */./*|*/.|*/../*|*/..)
        echo "!! ruta de instalación insegura: $INSTALL_HOME_ORIGINAL" >&2
        exit 1
        ;;
esac
if [[ "$INSTALL_HOME" != /* \
        || "$(basename -- "$INSTALL_HOME")" != "guionar" \
        || "$(dirname -- "$INSTALL_HOME")" == "/" \
        || "$INSTALL_HOME" == "$HOME" ]]; then
    echo "!! ruta de instalación insegura: $INSTALL_HOME_ORIGINAL" >&2
    exit 1
fi
case "$CONFIG_DIR" in
    /guionar|"$HOME"/guionar)
        echo "!! ruta de configuración insegura: $CONFIG_DIR" >&2
        exit 1
        ;;
esac

colapsar_separadores() {
    local valor="$1"
    while [[ "$valor" == *//* ]]; do
        valor="${valor//\/\//\/}"
    done
    printf '%s' "$valor"
}

borrar_propio() {
    local ruta="$1"
    if [[ -L "$ruta" ]]; then
        rm -f -- "$ruta"
    elif [[ -e "$ruta" ]]; then
        rm -rf -- "$ruta"
    fi
}

if [[ -f "$DESKTOP_PATH" && ! -L "$DESKTOP_PATH" ]] \
        && IFS= read -r primera <"$DESKTOP_PATH" && [[ "$primera" == "$MARCA"* ]]; then
    rm -f -- "$DESKTOP_PATH"
fi

# El ícono no lleva marca: sólo se borra si es idéntico al instalado.
ICONO_INSTALADO="$INSTALL_HOME/current/app/assets/guionar.svg"
if [[ -f "$ICON_PATH" && ! -L "$ICON_PATH" && -f "$ICONO_INSTALADO" ]] \
        && cmp -s -- "$ICON_PATH" "$ICONO_INSTALADO"; then
    rm -f -- "$ICON_PATH"
fi

for par in "guionar:$INSTALL_HOME/current/app/bin/guionar" \
        "guionar-uninstall:$INSTALL_HOME/uninstall.sh"; do
    destino="$BIN_DIR/${par%%:*}"
    if [[ -L "$destino" ]] \
            && [[ "$(colapsar_separadores "$(readlink -- "$destino")")" == "${par#*:}" ]]; then
        rm -f -- "$destino"
    fi
done

if [[ -L "$INSTALL_HOME" ]]; then
    echo "!! la raíz de instalación es un enlace simbólico; no se sigue ni elimina: $INSTALL_HOME" >&2
elif [[ -d "$INSTALL_HOME" ]]; then
    borrar_propio "$INSTALL_HOME/current"
    borrar_propio "$INSTALL_HOME/versions"
    rm -f -- "$INSTALL_HOME/installed.json"
    # Bash ya abrió este script: borrarlo no interrumpe la ejecución.
    rm -f -- "$INSTALL_HOME/uninstall.sh"
    rmdir -- "$INSTALL_HOME" 2>/dev/null || true
fi

if ((PURGE_DATA)); then
    borrar_propio "$CONFIG_DIR"
fi

if command -v update-desktop-database >/dev/null 2>&1; then
    update-desktop-database "$DATA_BASE/applications" >/dev/null 2>&1 || true
fi
if command -v gtk-update-icon-cache >/dev/null 2>&1; then
    gtk-update-icon-cache -q -t "$DATA_BASE/icons/hicolor" >/dev/null 2>&1 || true
fi

if ((PURGE_DATA)); then
    echo "==> GuionAR desinstalado. Se eliminó también su configuración."
else
    echo "==> GuionAR desinstalado. Tu configuración (~/.config/guionar) se conservó."
    echo "    Para eliminarla también: guionar-uninstall --purge-data"
fi
echo "    Si GuionAR sigue abierto, cerralo desde su ventana o la bandeja."
}

main "$@"
exit
