#!/usr/bin/env python3
"""Instalador de usuario de GuionAR desde la release extraída.

Lo invoca ``install.sh`` con un Python ya validado. Layout administrado bajo
``$XDG_DATA_HOME/guionar``::

    versions/<versión>-<id>/app/    módulos, bin/, assets/ y packaging/
    versions/<versión>-<id>/.venv/  PyQt6 fijado por constraints.txt
    current -> versions/<...>       symlink relativo, reemplazo atómico
    installed.json                  metadata mínima, escritura atómica
    uninstall.sh                    desinstalador independiente del release

Todo lo previo al swap ocurre en un directorio nuevo. Si algo falla, ese
directorio se elimina y ``current``, enlaces y launcher quedan como estaban.
La configuración (``~/.config/guionar``) nunca se toca, y tampoco una copia
del repositorio que se haya usado antes para abrir GuionAR.
"""

from __future__ import annotations

import argparse
import contextlib
from dataclasses import dataclass
import datetime as _dt
import fcntl
import json
import os
from pathlib import Path
import re
import secrets
import shutil
import subprocess
import sys
import tempfile

APP = "GuionAR"
MARCA_DESKTOP = ("# Generated by GuionAR install.sh. "
                 "Local edits may be replaced by a later install.")
MARCA_INCOMPLETA = ".guionar-incomplete"
MARCA_VERSION = ".guionar-version"  # bin/guionar la usa para hallar .venv
NOMBRE_VERSION = re.compile(r"^[0-9][0-9A-Za-z.+]*-[0-9a-f]{8}$")
MIB = 1024 * 1024
ESPACIO_MINIMO = 768 * MIB
COMANDO = "guionar"
COMANDO_UNINSTALL = "guionar-uninstall"
# Plantilla que usaba packaging/linux/install-desktop-entry.sh. Un launcher
# sólo se considera legacy propio si coincide con ella línea por línea y su
# Exec apunta a */bin/guionar --socket.
PLANTILLA_LEGACY = """[Desktop Entry]
Type=Application
Version=1.5
Name=GuionAR
GenericName=Teleprompter
Comment=Teleprompter flotante para leer un guion frente a la cámara
Exec=@EXEC@ --socket
Icon=guionar
Terminal=false
StartupNotify=false
Categories=AudioVideo;Video;
Keywords=teleprompter;guion;prompter;script;ParlAR;
"""
# Dentro de comillas cada " ` $ \\ lleva una barra y después la regla de
# strings duplica cada barra: un carácter especial queda como \\\\X.
_EXEC_LEGACY = re.compile(
    r'^Exec="(/(?:[^"\\`$]|\\\\(?:\\\\|["`$]))*/bin/guionar)" --socket$')
SMOKE = r"""
import os, sys
sys.path.insert(0, sys.argv[1])
from PyQt6.QtWidgets import QApplication
import bridge, desktop_shell, document_loader, guion, guionar
app = QApplication([])
overlay = guionar.TeleprompterOverlay(None, persistir=False)
overlay.show()
overlay.append_text("prueba")
app.processEvents()
overlay.close()
app.processEvents()
print("smoke-ok")
"""


class ErrorInstalacion(RuntimeError):
    """Fallo controlado: el mensaje es para la persona usuaria."""


def info(mensaje: str) -> None:
    print(f"==> {mensaje}", flush=True)


def aviso(mensaje: str) -> None:
    print(f"!! {mensaje}", file=sys.stderr, flush=True)


# ---------------------------------------------------------------------------
# Origen y destino
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class Origen:
    raiz: Path
    version: str

    @property
    def app(self) -> Path:
        return self.raiz / "app"

    @property
    def packaging(self) -> Path:
        return self.app / "packaging" / "linux"

    @property
    def constraints(self) -> Path:
        return self.raiz / "constraints.txt"

    @property
    def uninstall(self) -> Path:
        return self.raiz / "uninstall.sh"


def leer_version_app(app: Path) -> str:
    texto = (app / "guionar_version.py").read_text(encoding="utf-8")
    coincidencia = re.search(r'^__version__ = "([^"]+)"$', texto, re.M)
    if not coincidencia:
        raise ErrorInstalacion("guionar_version.py sin __version__")
    return coincidencia[1]


def detectar_origen(raiz: Path) -> Origen:
    raiz = raiz.resolve()
    if not ((raiz / "VERSION").is_file() and (raiz / "app").is_dir()):
        raise ErrorInstalacion(
            f"{raiz} no es una release de GuionAR. Descargá la release "
            "desde https://github.com/SGGaray/GuionAR/releases")
    version = (raiz / "VERSION").read_text(encoding="utf-8").strip()
    if leer_version_app(raiz / "app") != version:
        raise ErrorInstalacion("VERSION no coincide con la app; descargá "
                               "la release de nuevo")
    return Origen(raiz, version)


def versiones_python(origen: Origen) -> list[str]:
    archivo = origen.packaging / "python-versions.txt"
    return [linea.strip() for linea in archivo.read_text(
        encoding="utf-8").splitlines() if linea.strip()]


def verificar_python(origen: Origen) -> None:
    versiones = versiones_python(origen)
    if "%d.%d" % sys.version_info[:2] not in versiones:
        raise ErrorInstalacion(
            f"Esta versión de GuionAR soporta Python {versiones[0]}–"
            f"{versiones[-1]}.\nInstalá una versión compatible o descargá "
            "una release más nueva.")


def _sin_separadores_finales(valor: str) -> str:
    while valor != "/" and valor.endswith("/"):
        valor = valor[:-1]
    return valor


def validar_install_home(original: str, home: str) -> Path:
    valor = _sin_separadores_finales(original)
    partes = valor.split("/")
    ruta = Path(valor)
    if ("." in partes or ".." in partes or not ruta.is_absolute()
            or ruta.name != "guionar" or str(ruta.parent) == "/"
            or valor == _sin_separadores_finales(home)):
        raise ErrorInstalacion(f"ruta de instalación insegura: {original}")
    return ruta


@dataclass(frozen=True)
class Destino:
    home: Path
    install_home: Path
    bin_dir: Path
    desktop: Path
    icono: Path

    @classmethod
    def desde_entorno(cls, entorno=os.environ) -> "Destino":
        home = entorno.get("HOME", "")
        if not home or not os.path.isabs(home):
            raise ErrorInstalacion("HOME no está definido como ruta absoluta")
        data = Path(entorno.get("XDG_DATA_HOME") or f"{home}/.local/share")
        return cls(
            home=Path(home),
            install_home=validar_install_home(
                entorno.get("GUIONAR_INSTALL_HOME") or str(data / "guionar"),
                home),
            bin_dir=Path(entorno.get("GUIONAR_BIN_DIR")
                         or f"{home}/.local/bin"),
            desktop=data / "applications" / "guionar.desktop",
            icono=data / "icons" / "hicolor" / "scalable" / "apps" / "guionar.svg",
        )

    @property
    def versions(self) -> Path:
        return self.install_home / "versions"

    @property
    def current(self) -> Path:
        return self.install_home / "current"

    @property
    def metadata(self) -> Path:
        return self.install_home / "installed.json"

    @property
    def uninstall(self) -> Path:
        return self.install_home / "uninstall.sh"

    @property
    def lanzador(self) -> Path:
        """Ruta estable entre versiones: atraviesa ``current``."""
        return self.current / "app" / "bin" / "guionar"

    def enlaces(self) -> dict[Path, Path]:
        return {self.bin_dir / COMANDO: self.lanzador,
                self.bin_dir / COMANDO_UNINSTALL: self.uninstall}


# ---------------------------------------------------------------------------
# Launcher
# ---------------------------------------------------------------------------


def argumento_exec(ruta: Path) -> str:
    """Exec entre comillas según la especificación Desktop Entry."""
    texto = str(ruta)
    if not ruta.is_absolute():
        raise ErrorInstalacion("el ejecutable del launcher debe ser absoluto")
    if any(ord(c) < 32 or ord(c) == 127 for c in texto):
        raise ErrorInstalacion("el ejecutable contiene caracteres de control")
    # Mismo escape que install-desktop-entry.sh: regla de comillas, regla
    # de strings (duplica barras) y, además, % de los field codes.
    texto = re.sub(r'([\\"`$])', r"\\\1", texto)
    texto = texto.replace("\\", "\\\\").replace("%", "%%")
    return f'"{texto}"'


def renderizar_desktop(plantilla: str, lanzador: Path) -> str:
    if plantilla.count("@EXEC@") != 1:
        raise ErrorInstalacion("plantilla .desktop sin placeholder único")
    return f"{MARCA_DESKTOP}\n" + plantilla.replace(
        "@EXEC@", argumento_exec(lanzador))


def es_desktop_legacy(contenido: str) -> bool:
    """Reconoce sólo el launcher exacto de install-desktop-entry.sh."""
    esperadas = PLANTILLA_LEGACY.splitlines()
    lineas = contenido.splitlines()
    if len(lineas) != len(esperadas) or not contenido.endswith("\n"):
        return False
    for linea, esperada in zip(lineas, esperadas):
        if "@EXEC@" in esperada:
            if not _EXEC_LEGACY.match(linea):
                return False
        elif linea != esperada:
            return False
    return True


def estado_desktop(ruta: Path) -> str:
    """'ausente', 'propio', 'legacy' o 'ajeno'."""
    if not os.path.lexists(ruta):
        return "ausente"
    if ruta.is_symlink() or not ruta.is_file():
        return "ajeno"
    try:
        contenido = ruta.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        return "ajeno"
    if contenido.startswith(MARCA_DESKTOP + "\n"):
        return "propio"
    if es_desktop_legacy(contenido):
        return "legacy"
    return "ajeno"


# ---------------------------------------------------------------------------
# Operaciones atómicas
# ---------------------------------------------------------------------------


def escribir_atomico(destino: Path, contenido: bytes, modo: int) -> None:
    destino.parent.mkdir(parents=True, exist_ok=True)
    temporal = destino.with_name(f".{destino.name}.tmp-{secrets.token_hex(4)}")
    descriptor = os.open(temporal, os.O_WRONLY | os.O_CREAT | os.O_EXCL, modo)
    try:
        with os.fdopen(descriptor, "wb") as archivo:
            archivo.write(contenido)
            archivo.flush()
            os.fsync(archivo.fileno())
        os.chmod(temporal, modo)
        os.replace(temporal, destino)
    except BaseException:
        with contextlib.suppress(FileNotFoundError):
            temporal.unlink()
        raise


def symlink_atomico(destino: Path, target: str) -> None:
    destino.parent.mkdir(parents=True, exist_ok=True)
    temporal = destino.with_name(f".{destino.name}.tmp-{secrets.token_hex(4)}")
    os.symlink(target, temporal)
    try:
        os.replace(temporal, destino)
    except BaseException:
        with contextlib.suppress(FileNotFoundError):
            temporal.unlink()
        raise


@contextlib.contextmanager
def bloqueo(ruta: Path):
    """flock sobre el directorio raíz: no deja archivos de lock."""
    descriptor = os.open(ruta, os.O_RDONLY | os.O_DIRECTORY)
    try:
        try:
            fcntl.flock(descriptor, fcntl.LOCK_EX | fcntl.LOCK_NB)
        except BlockingIOError:
            raise ErrorInstalacion(
                "hay otra instalación de GuionAR en curso") from None
        yield
    finally:
        os.close(descriptor)


def verificar_espacio(ruta: Path, minimo: int) -> None:
    existente = ruta
    while not existente.exists():
        existente = existente.parent
    libre = shutil.disk_usage(existente).free
    if libre < minimo:
        raise ErrorInstalacion(
            f"espacio insuficiente en {existente}: libres {libre // MIB} MiB, "
            f"se necesitan al menos {minimo // MIB} MiB")


# ---------------------------------------------------------------------------
# Herramientas externas (sustituibles en tests)
# ---------------------------------------------------------------------------


class Herramientas:
    """Única frontera con venv/pip/subprocesos; todo con cwd ``/``."""

    def crear_venv(self, destino: Path) -> None:
        subprocess.run([sys.executable, "-m", "venv", str(destino)],
                       check=True, cwd="/")

    def pip_install(self, python: Path, argumentos: list[str]) -> bool:
        comando = [str(python), "-m", "pip", "install",
                   "--disable-pip-version-check", "--no-input", *argumentos]
        return subprocess.run(comando, check=False, cwd="/").returncode == 0

    def ejecutar(self, comando: list[str],
                 entorno: dict[str, str] | None = None
                 ) -> subprocess.CompletedProcess:
        return subprocess.run(
            comando, check=False, text=True, capture_output=True,
            timeout=120, cwd="/", env=entorno)


# ---------------------------------------------------------------------------
# Instalación
# ---------------------------------------------------------------------------


class Instalador:
    def __init__(self, origen: Origen, destino: Destino,
                 herramientas: Herramientas | None = None):
        self.origen = origen
        self.destino = destino
        self.h = herramientas or Herramientas()

    def verificar_propiedad(self) -> str:
        d = self.destino
        for enlace, target in d.enlaces().items():
            if not os.path.lexists(enlace):
                continue
            actual = re.sub(r"/+", "/", os.readlink(enlace)) \
                if enlace.is_symlink() else None
            if actual != str(target):
                raise ErrorInstalacion(
                    f"{enlace} existe y no pertenece a esta instalación")
        estado = estado_desktop(d.desktop)
        if estado == "ajeno":
            raise ErrorInstalacion(
                f"{d.desktop} ya existe y no fue generado por GuionAR; "
                "no se reemplaza")
        if d.install_home.is_symlink():
            raise ErrorInstalacion(
                f"la raíz de instalación es un enlace simbólico: {d.install_home}")
        if os.path.lexists(d.current) and not d.current.is_symlink():
            raise ErrorInstalacion(f"{d.current} no es un enlace de GuionAR")
        return estado

    def _entorno_smoke(self, temporal: Path) -> dict[str, str]:
        entorno = {k: v for k, v in os.environ.items()
                   if k in {"PATH", "LANG", "LC_ALL", "HOME"}}
        runtime = temporal / "run"
        runtime.mkdir(mode=0o700)
        entorno.update({
            "QT_QPA_PLATFORM": "offscreen",
            "XDG_CONFIG_HOME": str(temporal / "config"),
            "XDG_RUNTIME_DIR": str(runtime),
        })
        return entorno

    def _preparar(self, version_dir: Path) -> None:
        app = version_dir / "app"
        venv = version_dir / ".venv"
        python = venv / "bin" / "python"
        info("Copiando la aplicación")
        shutil.copytree(self.origen.app, app, symlinks=False)
        (app / "bin" / "guionar").chmod(0o755)

        info(f"Creando entorno aislado {version_dir.name}")
        self.h.crear_venv(venv)
        info("Instalando PyQt6")
        if not self.h.pip_install(python, [
                "-c", str(self.origen.constraints),
                "--only-binary=:all:", "PyQt6"]):
            raise ErrorInstalacion("pip no pudo instalar PyQt6")

        info("Validando PyQt6, QtPdf y GuionAR")
        with tempfile.TemporaryDirectory(prefix="guionar-smoke-") as tmp:
            entorno = self._entorno_smoke(Path(tmp))
            for descripcion, comando in (
                    ("PyQt6", [str(python), "-I", "-c",
                               "import PyQt6.QtCore, PyQt6.QtGui, "
                               "PyQt6.QtWidgets"]),
                    ("QtPdf", [str(python), "-I", "-c",
                               "from PyQt6.QtPdf import QPdfDocument"]),
                    ("smoke", [str(python), "-I", "-c", SMOKE, str(app)])):
                resultado = self.h.ejecutar(comando, entorno)
                if resultado.returncode != 0:
                    raise ErrorInstalacion(
                        f"validación de {descripcion} falló:\n"
                        + (resultado.stderr or resultado.stdout).strip()[-2000:])
            resultado = self.h.ejecutar(
                [str(app / "bin" / "guionar"), "--version"], entorno)
        esperado = f"{APP} {self.origen.version}"
        if resultado.returncode != 0 or resultado.stdout.strip() != esperado:
            raise ErrorInstalacion(
                f"guionar --version devolvió {resultado.stdout.strip()!r}; "
                f"se esperaba {esperado!r}")

    def _publicar(self, estado_desktop_previo: str) -> None:
        d = self.destino
        for enlace, target in d.enlaces().items():
            if not (enlace.is_symlink() and os.readlink(enlace) == str(target)):
                symlink_atomico(enlace, str(target))

        plantilla = (self.origen.packaging / "guionar.desktop.in").read_text(
            encoding="utf-8")
        escribir_atomico(
            d.desktop, renderizar_desktop(plantilla, d.lanzador).encode(), 0o644)
        if estado_desktop_previo == "legacy":
            info("Launcher anterior reemplazado; la copia del repositorio "
                 "no se modificó")
        info(f"Launcher en el menú: {d.desktop}")

        icono = (self.origen.app / "assets" / "guionar.svg").read_bytes()
        if (not d.icono.exists() or d.icono.is_symlink()
                or estado_desktop_previo in {"propio", "legacy"}
                or d.icono.read_bytes() == icono):
            if d.icono.is_symlink():
                d.icono.unlink()
            escribir_atomico(d.icono, icono, 0o644)
        else:
            aviso(f"{d.icono} existe y no es de GuionAR; se conserva")

        for comando in (
                ["update-desktop-database", str(d.desktop.parent)],
                ["gtk-update-icon-cache", "-q", "-t", str(d.icono.parents[2])]):
            if shutil.which(comando[0]):
                self.h.ejecutar(comando)

    def _escribir_metadata(self, version_dir: str, previous: str | None) -> None:
        datos = {
            "app": APP,
            "version": self.origen.version,
            "current": version_dir,
            "previous": previous,
            "installed_at": _dt.datetime.now(_dt.timezone.utc)
            .replace(microsecond=0).isoformat().replace("+00:00", "Z"),
        }
        escribir_atomico(self.destino.metadata,
                         (json.dumps(datos, indent=2) + "\n").encode(), 0o644)

    def _podar(self, conservar: set[str]) -> None:
        for entrada in sorted(self.destino.versions.iterdir()):
            if (f"versions/{entrada.name}" in conservar
                    or entrada.is_symlink() or not entrada.is_dir()):
                continue
            if NOMBRE_VERSION.match(entrada.name) and (
                    entrada / MARCA_VERSION).is_file():
                info(f"Eliminando versión antigua {entrada.name}")
                shutil.rmtree(entrada)

    def _current_previo(self) -> str | None:
        d = self.destino
        if not d.current.is_symlink():
            return None
        target = os.readlink(d.current)
        partes = target.split("/")
        if not (len(partes) == 2 and partes[0] == "versions"
                and NOMBRE_VERSION.match(partes[1])):
            raise ErrorInstalacion(
                f"{d.current} apunta a un destino no administrado: {target}")
        return target if (d.install_home / target).is_dir() else None

    def instalar(self) -> tuple[str, str | None]:
        d = self.destino
        estado = self.verificar_propiedad()
        verificar_espacio(d.install_home, ESPACIO_MINIMO)
        raiz_nueva = not d.install_home.exists()
        d.install_home.mkdir(parents=True, exist_ok=True)
        with bloqueo(d.install_home):
            previous = self._current_previo()
            versions_nuevo = not d.versions.exists()
            d.versions.mkdir(exist_ok=True)
            nombre = f"{self.origen.version}-{secrets.token_hex(4)}"
            version_dir = d.versions / nombre
            version_dir.mkdir()
            (version_dir / MARCA_INCOMPLETA).write_text("", encoding="utf-8")
            (version_dir / MARCA_VERSION).write_text(
                f"{APP} {self.origen.version}\n", encoding="utf-8")
            try:
                self._preparar(version_dir)
                (version_dir / MARCA_INCOMPLETA).unlink()
            except BaseException:
                aviso("La instalación nueva falló; se descarta sin tocar la "
                      "instalación vigente")
                shutil.rmtree(version_dir, ignore_errors=True)
                for vacio, creado in ((d.versions, versions_nuevo),
                                      (d.install_home, raiz_nueva)):
                    if creado:
                        with contextlib.suppress(OSError):
                            vacio.rmdir()
                raise

            relativo = f"versions/{nombre}"
            symlink_atomico(d.current, relativo)
            self._publicar(estado)
            escribir_atomico(d.uninstall, self.origen.uninstall.read_bytes(),
                             0o755)
            self._escribir_metadata(relativo, previous)
            self._podar({relativo} | ({previous} if previous else set()))
        return relativo, previous


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="install.sh")
    parser.add_argument("--origen", type=Path, required=True)
    args = parser.parse_args(argv)
    try:
        origen = detectar_origen(args.origen)
        verificar_python(origen)
        destino = Destino.desde_entorno()
        _relativo, previous = Instalador(origen, destino).instalar()
    except ErrorInstalacion as exc:
        aviso(str(exc))
        return 1
    except (OSError, ValueError, subprocess.SubprocessError) as exc:
        aviso(f"la instalación falló: {exc}")
        return 1
    except KeyboardInterrupt:
        aviso("instalación interrumpida; la instalación vigente no cambió")
        return 130

    info(f"GuionAR {origen.version} instalado. Comandos: "
         f"{destino.bin_dir}/{COMANDO} y {destino.bin_dir}/{COMANDO_UNINSTALL}")
    if previous:
        print("    Si GuionAR está abierto, cerralo y volvé a abrirlo desde el "
              f"menú para usar {origen.version}.")
    if f":{destino.bin_dir}:" not in f":{os.environ.get('PATH', '')}:":
        aviso(f"{destino.bin_dir} no está en PATH; agregalo para invocar los "
              "comandos por nombre")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
